GeoscienceAustralia/PyRate

- pyrate/conversion/base.py
Nothing concrete at this stage.  Just some ideas and future concepts that could be handy down the line.
The Conversion class is an idea to enable a "driver" like concept for handling the I/O of different formats.
eg
* GAMMA raw binary
* GAMMA TIFF
* ROIPAC raw binary
* SNAP BEAM-DIMAP
* SNAP HDF5
The other functions are simplifying already existing functions.  Just written in a way that they're more generic, and only do one base thing, like write a file.  Not prep metadata, or figure out what kind of file i am, which occurs all during the write phase.  So just some ideas on how to split those components out.
I've given examples for both rasterio and gdal-python bindings, and should work under Python2.7 and Python3.  No tests, but the goal was more to present some ideas and concepts, so I …
> Generalise write geotif

- pyrate/mst.py
- requirements-dev.txt
- setup.py
Issue was that .edges() (and nodes etc) have changed from returning list/dict copies to nx's own View objects. There was a guard checking if the mst edges was a list instance before iterating over them. Changing this guard to check if it's an instance of EdgeView fixes the problem.
The difference is that these View objects now return dynamic views of the edges/nodes that change as the graph/tree changes. More details [here](https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html).
> Update mst to work with networkx v2.

- .travis.yml
This will only trigger travis to run on develop, master and release- (assuming we'll use the "release" prefix for dev -> master staging branches). This can be changed in .travis.yml.
> Limit travis builds

- pyrate/mpiops.py
- requirements-dev.txt
- setup.py
Update to the latest version of mpi4py. This is operating in conjunction with openmpi 2.1.1. Workflow carries out successfully on Raijin but unit tests are still an issue (#190 ).
> Upgrade mpi4py 2.0.0 -> 3.0.2

- pyrate/__init__.py
- pyrate/config.py
- pyrate/linrate.py
- pyrate/mst.py
- pyrate/orbital.py
- pyrate/ref_phs_est.py
- pyrate/refpixel.py
- pyrate/scripts/converttogtif.py
- pyrate/scripts/main.py
- pyrate/scripts/run_prepifg.py
- pyrate/shared.py
- pyrate/timeseries.py
This ties to the joblib verbosity to the PyRate verobisty - joblib messages will be disabled unless "DEBUG" is set as log level. I've also removed the MPI warning by setting an environment variable in the __init__ of the pyrate module.
> Turn down parallel job logging messages

- docs/usage.rst
- input_parameters.conf
- pyrate/core/config.py
- pyrate/core/gamma.py
- tests/common.py
- tests/test_data/small_test/conf/pyrate_gamma_test.conf
- tests/test_data/small_test/gamma_obs/headers
- tests/test_gamma_vs_roipac.py
- tests/test_prepifg.py
Rather than relying on extensions to identify file types we will now use lists for coherence and GAMMA header files in the same way as intergerogram file lists.
The new parameters are `slcfilelist` and `cohfilelist.`
Another addition is that `cohfiledir` and `slcFileDir` will fallback on `obsdir` as a default if they aren't provided.
Usage documentation has been updated to reflect this.
> Implement file lists for coherence and header files.

- input_parameters.conf
- pyrate/__init__.py
- pyrate/__main__.py
- pyrate/core/config.py
- pyrate/process.py
- tests/test_config.py
This aims to solve the issue of needing access to cropped/resampled interferograms for certain parameter checks. It does this by introducing the previously discussed idea of selectively running validation functions based on the current workflow step being run. _Note that bounds checking is still performed for every parameter regardless of what step is being run_ - this is an improvement that can be made in future.
The main thing to test here is that the previous failing checks (orbital looks, refx/y) now work.
> Validation refactor

- scripts/nci_load_modules.sh
Activate the venv from a configured location instead of "~". Falls back to the previous behaviour if no PYRATE_VENV is set in the environment.
> Configurable venv location in nci_load_modules.

- input_parameters.conf
- pyrate/core/timeseries.py
- pyrate/default_parameters.py
- pyrate/merge.py
- pyrate/process.py
- tests/test_data/small_test/conf/pyrate_gamma_test.conf
- tests/test_data/small_test/conf/pyrate_roipac_test.conf
- tests/test_merge.py
- make saving tsincr files (npy or tif) optional.
- controlled by new config parameter `savetsincr`
- default is on (`savetsincr=1`)
- saving of tscuml files is unaffected.
> Optional save of tsincr files

- README.rst
- pyrate/core/gdal_python.py
- requirements.txt
- tests/test_gdal_python.py
`Pillow` is a required python dependency in PyRate but is only used in one function `pyrate.core.gdal_pyrate.crop`, which itself is not used in the main workflow. It is only used as a comparison tool in a unit test.
`glob2` is a requirement but not used anywhere.
I propose we remove these package dependencies and the functions/tests that require them
> Remove Pillow dependency

- pyrate/core/shared.py
- tests/test_gamma.py
- tests/test_roipac.py
This PR removes a long-held rule in `conv2tif` that the input rasters must have equal X and Y pixel resolutions.
This issue was identified by an external user who has unequal X/Y resolution images - see https://github.com/GeoscienceAustralia/PyRate/issues/305
In this PR I have removed:
- one check in the function `shared.write_fullres_geotiff`, used only in `conv2tif` step
- the check function associated with the above
- two tests associated with the check function
> Remove requirement for equal X and Y resolution in conv2tif

- input_parameters.conf
- pyrate/core/stack.py
- pyrate/core/timeseries.py
- pyrate/default_parameters.py
- tests/test_data/small_test/conf/pyrate_roipac_test.conf
- tests/test_stackrate.py
- tests/test_timeseries.py
1. I have added a switch to the config file, which allows the user to specify whether they would like the velocity error maps to represent 1- or 2-sigma errors. This switch applies to the error maps produced by both `stack` and `timeseries` methods. The default is 2-sigma (95% confidence interval) because this is the standard for uncertainty communication in many fields of science.
2. I modified the test suite, specifically `test_timeseries.py` and `test_stackrate.py`, to manually specify 1-sigma errors in the default parameters dictionary. This is for compatibility with the legacy test datasets which have 1-sigma error maps.
3. I added a new test to `test_timeseries.py` which confirms that the switch actually produces a 2-sigma error map when this is specified.
> Add switch to specify uncertainty communication in rate/velocity error maps

- input_parameters.conf
- pyrate/configuration.py
- pyrate/constants.py
- pyrate/core/shared.py
- pyrate/core/stack.py
- pyrate/core/timeseries.py
- pyrate/default_parameters.py
- pyrate/merge.py
- tests/test_data/cropA/pyrate_mexico_cropa.conf
- tests/test_data/small_test/conf/pyrate_gamma_test.conf
- tests/test_merge.py
- tests/test_stackrate.py
- tests/test_timeseries.py
@mcgarth edit:
This PR implements a simple signal polarity conversion, which is applied to output geotiff products generated during the MERGE step. Data sign is not affected in the other processing steps. Default is multiplying the output data arrays by -1. This ensures GA's standard input interferograms are converted such that PyRate outputs have range increases as negative and range decreases as positive.
- Metadata for `signal_polarity` and `velerror_nsig` has been added to the geotiffs
- Info messages have been added to MERGE step to report on conversions being applied
> signal polarity configuration implemented and tested

- pyrate/core/gamma.py
- tests/test_data/gamma/20090713-20090817_base.par
- tests/test_data/gamma/20160114-20160126_base.par
- tests/test_data/gamma/20160114-20160126_base_init.par
- tests/test_gamma.py
This PR adds support for reading and using the Initial baseline estimates from GAMMA `*base.par` files.
The Precise baseline estimate will be used if it is found (i.e. if one of the TCN components is non-zero), otherwise the Initial baseline estimates will be read.
This change is required to support interferograms where precise baseline estimation has been skipped (i.e. when the orbital state vectors are deemed adequate to solve for the orbital phase contribution. This is usually the case for Sentinel-1).
> Add support for GAMMA initial baseline estimates

- pyrate/core/ref_phs_est.py
This PR introduces a circumventive measure to address the Issue identified at: https://github.com/GeoscienceAustralia/PyRate/issues/310 
Specifically, I add a small value of 1e-20 to the reference phase that is subtracted from each interferogram. This avoids pixels taking the exact value of zero (0.0) and possibly being converted to NaN downstream in the workflow.
> Fix issue 310

- pyrate/core/gamma.py
- tests/test_gamma.py
Very small PR to simply generate a clearer error message for when there are too many parameter files given to PyRate ini the lists. 
- `manage_headers()` in `pyrate/core/gamma.py` is designed to read and combine header information from a list of 2 MLI.par files or a single DEM.par file.
- The iff condition statement at `line 457` controls the flow: https://github.com/GeoscienceAustralia/PyRate/blob/c3054c569b4b1827b61326741277606bc47e8463/pyrate/core/gamma.py#L444-L471
- if the user accidently has more than 2 MLI.par files in their list (e.g. because of multiple polarisations), then this conditional statement will will not apply. 
- I have just added am `elif` condition to raise an error if the list of header files is > 2.
> Raise exception when too many header files are provided

- pyrate/core/mpiops.py
- pyrate/core/phase_closure/sum_closure.py
- tests/phase_closure/test_sum_closure.py
memory optimisations during sum closure
> [phase closure] sum closure memory opt [ci skip]

- pyrate/core/phase_closure/sum_closure.py
- scripts/plot_ifgs.py
- tests/phase_closure/test_plot_closure.py
Was having another issue with `sum_phase_closures` which was related to the numpy-array-in-a-dictionary design pattern we're using for inter-process communication - this simply doesn't work with big stacks of interferograms because if the limit on maximum size of a pickle, so I replaced it with a preallocated buffer and a call to `Gatherv`, along with the associated calculations of buffer sizes and stuff for each process.
> Replace dictionaries with buffers when merging loop closure calculations between processes [ci skip]

- pyrate/core/ref_phs_est.py
@mcgarth noticed a bug where areas outside the frame contained non-NaN values in the phase closure loop plots. I traced this back to the reference phase subtraction - this was done without masking the no-data values in the source dataset, so if the no-data val was zero, no-data pixels would become non-zero after subtracting the reference phase, and then be treated as valid pixels downstream. This PR converts no-data pixels to NaN before doing ref phase subtraction.
> Fix reference phase bug

- pyrate/core/phase_closure/closure_check.py
This PR changes the method we use to drop interferograms from the next iteration of phase closure checking - currently, a misclosure in a pixel for *any* loop the ifg appears in counts towards the comparison with `avg_ifg_err_thr`. If we have a large stack with many loops, an unwrapping error in one ifg will result in misclosures for many other ifgs, so this method means we end up dropping a lot of good interferograms.
The PR uses a stricter criterion - how many pixels have misclosures for *all* loops the ifg appears in? In my experiments, this results in keeping a lot more good ifgs for large stacks, and as a bonus is consistent with the logic we use to mask unwrapping errors in the final output of the phase closure module.
> Change method to drop ifgs with unwrapping errors in phase closure iterations

- utils/plot_correction_files.py
This script is designed to plot the correction files (NumPy), against the original interferogram and the corrected interferogram (GeoTIFFs) to aid user's interpretation of corrections and help debugging with PyRate. 
Here is an example where from left to right is original IFG (`interferogram_dir/`), correction applied (`orbit_error_dir/`), and resulting corrected IFG (`temp_mlooked_dir/`):
**Help Output**
**Example Usage:**
`python3 ~/PyRate/utils/plot_correction_files.py ./interferogram_dir ./orbit_error_dir ./temp_mlooked_dir ./plot_save_dir 1 10`
_the last two arguments will indicate that it will plot from the 1st to the 10th IFG (10 separate PNGs), this can be changed to any range within the maximum number of IFGs in user PyRate directory. Using `1 1 ` will plot the 1st only_ …
> Add plotting script for correction files

- pyrate/core/dem_error.py
- tests/test_dem_error.py
_This is a small PR for some additions to the `dem_error.py` file, we should create a new PR for some proper testing of the DEM error corrections._
**The per-pixel DEM error estimation loop would fail because the loop would contain NaNs from out of frame regions**
- added a for loop skip in dem error estimation for pixels with NaNs
**The baseline metadata in the IFG GeoTIFFs were not being updated because of the use of np.mean in the presence of NaNs**
- converted 2x np.mean() functions to np.nanmean()
_I also did some code tidying_
> Bugfix: Detect and ignore NaNs in per-pixel dem error calculation

- pyrate/core/refpixel.py
This is a small PR that simplifies the way that the user supplied reference pixel is validated (confirmed to be within spatial extent). Without this fix, PyRate does not work if trying to crop in combination to supplying reference pixel coordinates - a very common user case. 
It is associated with this issue: https://github.com/GeoscienceAustralia/PyRate/issues/360
**Recommended Review Strategy**
On your own testing dataset, run PyRate with the different combinations of cropping and user supplied reference pixel coordinates to confirm it is working for you and has also not broken anything. 
**The Problem**
PyRate gives configuration options for the user to determine where the reference pixel will be `refx` and `refy` in longitude and latitude. There is also the option to crop the dataset …
> Fix and simplify how user supplied reference pixel is validated

- pyrate/merge.py
- tests/test_merge.py
This is a small PR with a very small code change. It relates to the output files in the `velocity_dir` where the Y-intercept file `linear_intercept.tif` is not sign-reversed like the other output files when the user set config parameter `signal_polarity: -1` is set. 
See this issue for more details: https://github.com/GeoscienceAustralia/PyRate/issues/353
**Description**
- A part of the PyRate output is a GeoTIFF of Y-Intercept values (`linear_intercept.tif`) for each pixel to accompany the GeoTIFF containing rate values estimated by PyRate from the per pixel cumulative time series. 
- There is an option in PyRate configuration file to reverse the sign of the line-of-sight values so that the time series makes physical sense `signal_polarity: -1`. 
- The sign change occurs in the _merge_ …
> Fix wrong sign in Y-intercept output file

- pyrate/core/prepifg_helper.py
- pyrate/merge.py
This is a small PR that adds some simple metadata to the output files in the velocity directory. 
**Specifically**
Here are the three changes and their associated GitHub issues:
1. Add latitude and longitude coordinates of reference pixel to the output GeoTIFFs in `velocity_dir` (https://github.com/GeoscienceAustralia/PyRate/issues/358).
2. Add median azimuth of the LOS vector to the output GeoTIFFS in `velocity_dir` (https://github.com/GeoscienceAustralia/PyRate/issues/359).
3. Just a small correction to an error message which was stating the wrong condition (https://github.com/GeoscienceAustralia/PyRate/issues/362)
**Recommended Review Strategy**
In addition to checking that none of these break your processing workflow, here are some things to check regarding  the above points. 
1. …
> Add metadata to output files
